### ISSUE TITLE
Change openapi.json base URL

### ISSUE THREAD

**Issue by AustinGil** [wesleytodd/express-openapi#17]
I have an Express API that sites behind an NGINX proxy server. The API runs on a child route (`/api`). So all my express routes are defined as `/api/some-route`.

I tried setting up the redoc UI with  `app.use('/api/redoc', oapi.redoc);`. When I go to `/api/redoc` I get a UI that I assume is redoc, but it has an error saying 

```
Something went wrong...
"https://localhost:3000/openapi.json" is not a valid JSON Schema
Stack trace
SyntaxError: "https://localhost:3000/openapi.json" is not a valid JSON Schema
    at Function.syntax (https://localhost-core/napi/redoc/redoc.standalone.js:29:28051)
    at https://localhost-core/napi/redoc/redoc.standalone.js:41:54299

ReDoc Version: 2.0.0-rc.45
Commit: aa53416d
```

From there, I've tried `app.use('/api', oapi);`. Then `/api/openapi.json` works fine, but the redoc UI is still trying to get the json at `/openapi.json`

Is there a way to tell the UI to look at the prefixed path instead?

**Comment by AustinGil** [comment]
OK, I was able to look in the source code to find my answer. It's possible to pass other parameters to the openapi function: If your first parameter is a string, it will use that as the path prefix:
```
const openapi = require('@wesleytodd/openapi')

const oapi = oapi('/napi/openapi',
  {
    openapi: '3.0.0',
    info: {
      // ...
      },
    },
);
```
